// GENERATED by native/tools/build-js-bundle.mjs - do not edit. Classic script for JavaScriptCore; defines the global `PogoCore`.
// Source: Pogo Assist+ JavaScript, commit 97212e7e42fd9ab07d6ea427d98c5bd61f069158 (branch extractor-cpm-speed). Rebuild: node native/tools/build-js-bundle.mjs --repo <checkout> --out <dir>
// SHA-256 of each source file in the bundle:
//   7575d8e6a1230917670538d627e8dd0578c870f4ab0d938906fbfd5df0204d5f  src/extract/names.js
//   0a4b9bed98f1bca47b75e7fe16d7c1fb3d0325e4b968edd63144f3c93b255dce  src/extract/merge.js
//   022d56fd2da864188c96991d7ac4fba9349505e7c7c3e3a04c301c0c19fe21d7  src/cpm.js
//   dff9551cbdc4e32c89bff28e51c055a12b6efca973d2ea59de11d2ee719ba356  src/extract/solve.js
//   043fd52a238b4c9be07474e2df5e499054fc95d54284d26f4bd005677c157e94  src/cost.js
//   4b8025098171508c24b403f7ef0aaec0f9973228ef309aa6a305ef31cfceae75  src/extract/pipeline.js
//   4c51e138381908bea80e26e007bb6d5776dff0671bc842aa906b0091aa91e741  src/extract/batch.js
//   c8fe9222af1c82bb3f1e1593927c10fc9c08920940af0f2afa7b5b3f44e433f5  src/gamemaster.js
//   b8a3abe53b0c1ba6447c934d0d963651028b8ccef354f95cbec8329efcdde8f2  src/data.js
//   3f651cbae75d16534287e5837c36757775fba1c94391cc0081845ef5e0efdd10  src/advise.js
//   bcef25b2d28819219c4e8be7dfef7c773015171986e3147482b68efc6f4e7647  src/csv.js
//   325006b8d58a9b4cf8708cb1612a389c57f48b25d6bdf474a4e8fbc3ca2802c4  src/import/pokegenie.js
// SHA-256 of the data files copied beside it:
//   946db90132eb291521b00c2402b8d23170bcdf71402941cd1e1ce05141e1ddc3  data/gamemaster.json
//   7937da2d70645eecbba076597e48959671df2adef7aa2ce7294b8bb1de73441b  data/tiers.json
//   079547d64e5cf7f635cb953bedd5cf1c6c1cc0c8f1b050eaca7754d8c83ff0f8  data/pvp-rankings.json
(function (global) {
'use strict';
const __modules = Object.create(null);
function __def(path, fn) { __modules[path] = fn(); }
function __use(path) { const m = __modules[path]; if (!m) throw new Error("PogoCore: module not loaded: " + path); return m; }
__def("src/extract/frame.js", function () { const cut = (n) => function () { throw new Error(n + " is not part of the app core"); }; return { readFrame: cut("readFrame") }; });
__def("src/extract/names.js", function () {
// Match an OCR'd name to the species the game would have shown. The game prints the base name,
// with "Mega" / "Alolan" / "Galarian" style prefixes; other forms (Hero, Altered, Origin...) are
// not in the name, so one display name can map to several game-master species. The solver
// picks between those by CP and HP.

const REGIONAL = { alolan: 'Alola', galarian: 'Galar', hisuian: 'Hisui', paldean: 'Paldea' };
// The game prints "Nidoran♀" and "Nidoran♂". The OCR cannot read the symbol (it is not in the
// whitelist and comes out as nothing or one stray letter), so both share the display name
// "Nidoran" and the solver tells them apart by their stats. The export uses Poke Genie's names.
const NIDORAN = { nidoran_female: 'Nidoran♀', nidoran_male: 'Nidoran♂' };

/** Base name and Poke Genie style form ("", "Hero", "Mega Y", "Alola") of a game-master species. */
function nameAndForm(species) {
  const m = species.speciesName.match(/^(.*?)\s*\((.*)\)$/);
  const base = m ? m[1] : species.speciesName;
  const form = m ? m[2] : '';
  const nidoran = NIDORAN[species.speciesId];
  if (nidoran) return { name: nidoran, form: '' };
  return { name: base, form: REGIONAL[form.toLowerCase()] ?? form };
}

/** Candidate display names from the game master: [{ display, name, form, speciesIds: [] }]. */
function displayNames(gm) {
  const byDisplay = new Map();
  const add = (display, name, form, speciesId) => {
    const key = normalise(display);
    if (!byDisplay.has(key)) byDisplay.set(key, { display, name, form, speciesIds: [] });
    byDisplay.get(key).speciesIds.push(speciesId);
  };
  for (const p of gm.byId.values()) {
    if (p.speciesId.endsWith('_shadow')) continue; // same name on screen; the shadow flag is elsewhere
    if (NIDORAN[p.speciesId]) { add('Nidoran', 'Nidoran', '', p.speciesId); continue; }
    const m = p.speciesName.match(/^(.*?)\s*\((.*)\)$/);
    const base = m ? m[1] : p.speciesName;
    const form = m ? m[2] : '';
    const lower = form.toLowerCase();
    if (/^mega( [xy])?$|^primal$/.test(lower)) add(`${lower.startsWith('mega') ? 'Mega' : 'Primal'} ${base}${/ [xy]$/.test(lower) ? ' ' + form.slice(-1).toUpperCase() : ''}`, base, form, p.speciesId);
    else if (REGIONAL[lower]) add(`${form} ${base}`, base, REGIONAL[lower], p.speciesId);
    else add(base, base, form, p.speciesId);
  }
  return [...byDisplay.values()];
}

function normalise(text) {
  return String(text).normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase().replace(/[^a-z0-9 ]/g, ' ').replace(/\s+/g, ' ').trim();
}

/** Levenshtein distance. */
function distance(a, b) {
  const m = a.length, n = b.length;
  if (!m) return n; if (!n) return m;
  let prev = Array.from({ length: n + 1 }, (_, j) => j);
  for (let i = 1; i <= m; i++) {
    const cur = [i];
    for (let j = 1; j <= n; j++) cur[j] = Math.min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1));
    prev = cur;
  }
  return prev[n];
}

/**
 * Best candidate for an OCR'd name. Tries the whole text, then the text with stray one-letter or
 * punctuation tokens dropped (the edit-pencil icon often reads as a dot or a letter). Returns
 * { candidate, distance, text, whole } or null when nothing is close enough; `whole` says the match
 * used the whole text (trailing one-letter tokens aside), not the text with a word dropped.
 */
function matchName(text, candidates, { maxRatio = 0.25 } = {}) {
  const variants = new Set();
  const norm = normalise(text);
  if (!norm) return null;
  variants.add(norm);
  const tokens = norm.split(' ');
  variants.add(tokens.filter((t) => t.length > 1).join(' '));
  // The pencil icon sits after the name, so only trailing one-letter tokens may be dropped from a
  // "whole" match; a stray token in front could be what is left of "Alolan".
  const trimmed = [...tokens];
  while (trimmed.length > 1 && trimmed[trimmed.length - 1].length === 1) trimmed.pop();
  const wholeText = new Set([norm, trimmed.join(' ')]);
  if (tokens.length > 1) { variants.add(tokens.slice(1).join(' ')); variants.add(tokens.slice(0, -1).join(' ')); }
  // "Nidoran" plus at most one stray character is Nidoran with its gender symbol misread; without
  // this it is as close to "Nidorino" as to "Nidoran". Checked on the whole text first, then on
  // the text with a word dropped (an overlay can add a word after the name).
  // `attached`: a letter stuck to the name ("Nidorano"), which a misread Nidorino or Nidorina
  // also gives; the pipeline does not let such a frame interrupt a run of either.
  const nidoran = candidates.find((c) => normalise(c.display) === 'nidoran');
  if (nidoran) for (const v of variants) {
    if (/^nidoran ?[a-z0-9]?$/.test(v)) return { candidate: nidoran, distance: 0, text: 'nidoran', whole: wholeText.has(v), symbol: true, attached: v.length === 8 && !v.includes(' ') };
  }
  let best = null;
  for (const v of variants) {
    if (!v) continue;
    for (const c of candidates) {
      const key = normalise(c.display);
      const d = distance(v, key);
      const limit = Math.max(1, Math.floor(key.length * maxRatio));
      // Equally near, "Nidoran" gives way ("Nidorin" is Nidorina or Nidorino with a letter lost).
      const yields = best && d === best.distance && best.candidate.display === 'Nidoran' && c.display !== 'Nidoran';
      if (d <= limit && (!best || d < best.distance || yields || (d === best.distance && v.length > best.text.length && c.display !== 'Nidoran'))) best = { candidate: c, distance: d, text: v, whole: wholeText.has(v) };
    }
  }
  return best;
}
return { nameAndForm, displayNames, normalise, distance, matchName };
});
__def("src/extract/merge.js", function () {
// Turn per-frame readings into one row per Pokémon. Consecutive frames that could be the same
// Pokémon form a run: same name, and the CP, HP and bar reads do not contradict each other (a
// dropped or invented digit in one CP read is not a contradiction; a different HP is).
// Unreadable frames (mid-swipe) do not break a run. Within a run the fields are decided by vote;
// the pipeline then validates the CP candidates with the solver. Adjacent rows that are the
// same Pokémon settled twice are merged; non-adjacent identical rows are never merged.

/** Identity of a frame reading, or null when the frame did not identify a Pokémon. */
function identity(r) {
  return r && r.cp && r.name ? `${r.name}|${r.cp}` : null;
}

/** Two CP reads that could be the same number: equal, one digit different, or one digit dropped. */
function cpSimilar(a, b) {
  const x = String(a), y = String(b);
  if (x === y) return true;
  if (x.length === y.length && x.length >= 3) { let d = 0; for (let i = 0; i < x.length; i++) if (x[i] !== y[i]) d++; return d <= 1; }
  const [s, l] = x.length < y.length ? [x, y] : [y, x];
  if (l.length - s.length !== 1 || s.length < 2) return false;
  for (let i = 0; i < l.length; i++) if (l.slice(0, i) + l.slice(i + 1) === s) return true;
  return false;
}

const hpAgree = (a, b) => !a || !b || a.max === b.max;
/** Bars settle to whole units; a read far from whole units is mid-animation and says nothing. */
const SETTLED = 0.7;
/** Two bar reads agree when either is unsettled, or both are settled and equal. */
function ivsCompatible(a, b, ca = 1, cb = 1) {
  if (!a || !b || ca < SETTLED || cb < SETTLED) return true;
  return a.atk === b.atk && a.def === b.def && a.hp === b.hp;
}

/**
 * Group consecutive compatible readings into runs: [{ key, frames: [reading] }]. A frame joins the
 * current run when it is compatible with the previous frame and with the run as a whole: the
 * run's HP (first read), its fullest bar read, and its most-read CP.
 */
function groupRuns(readings) {
  const runs = [];
  let cur = null;
  for (const r of readings) {
    if (!identity(r)) continue;
    if (cur && joins(cur, r)) {
      cur.frames.push(r);
      if (r.hp && !cur.hp) cur.hp = r.hp;
      if (r.ivs && r.ivConfidence >= SETTLED && !cur.ivs) cur.ivs = r.ivs;
      for (const c of r.cpReads ?? [r.cp]) cur.cpCounts.set(c, (cur.cpCounts.get(c) ?? 0) + 1);
    } else {
      cur = { key: identity(r), frames: [r], hp: r.hp ?? null, ivs: r.ivs && r.ivConfidence >= SETTLED ? r.ivs : null, cpCounts: new Map((r.cpReads ?? [r.cp]).map((c) => [c, 1])) };
      runs.push(cur);
    }
  }
  return runs;
}

function joins(run, r) {
  const last = run.frames[run.frames.length - 1];
  if (last.name !== r.name) return false;
  if (!hpAgree(run.hp, r.hp)) return false;
  const topCp = [...run.cpCounts.entries()].sort((a, b) => b[1] - a[1])[0][0];
  const reads = r.cpReads ?? [r.cp];
  // Contradictory settled bars split the run only when the CP read also differs: with the same
  // CP a mid-animation read can look settled by chance, but a different CP and different bars
  // is another Pokémon (adjacent hatched Meltan at CP 150 and 151, say).
  if (run.ivs && r.ivs && (r.ivConfidence ?? 0) >= SETTLED && !ivsCompatible(run.ivs, r.ivs) && !reads.includes(topCp)) return false;
  if (reads.some((c) => cpSimilar(c, last.cp) || cpSimilar(c, topCp))) return true;
  // A badly garbled CP read on a frame whose HP and settled bars match the run exactly is still the same Pokémon.
  return Boolean(run.hp && r.hp && run.ivs && r.ivs && (r.ivConfidence ?? 0) >= SETTLED && run.hp.max === r.hp.max && run.ivs.atk === r.ivs.atk && run.ivs.def === r.ivs.def && run.ivs.hp === r.ivs.hp);
}

/** Values ranked by count (ties: the later value); returns [{ v, n }]. */
function ranked(values, keyOf = (v) => JSON.stringify(v)) {
  const counts = new Map();
  let i = 0;
  for (const v of values) {
    i++;
    if (v === null || v === undefined) continue;
    const k = keyOf(v);
    const e = counts.get(k) ?? { v, n: 0, last: 0 };
    e.n++; e.v = v; e.last = i; counts.set(k, e);
  }
  return [...counts.values()].sort((a, b) => b.n - a.n || b.last - a.last);
}

function vote(values, keyOf) { return ranked(values, keyOf)[0]?.v ?? null; }

/**
 * Collapse a run to one reading. CP candidates are every CP read in the run ranked by count (the
 * pipeline picks the first that the solver accepts); HP by vote; the bars from the frame with the
 * fullest confident read (the latest point of the fill animation).
 */
function collapseRun(run) {
  const frames = run.frames;
  const cpCandidates = ranked(frames.flatMap((f) => f.cpReads ?? [f.cp]));
  const hp = vote(frames.map((f) => f.hp?.max ?? null));
  // Bars: the panel animates from the previous Pokémon's bars to this one's, so only settled
  // reads (whole units) count; they are voted, ties to the later frame. With no settled read the
  // last read is the closest to the final state and is flagged.
  const settled = frames.filter((f) => f.ivs && f.ivConfidence >= SETTLED);
  const ivsDisagree = new Set(settled.map((f) => `${f.ivs.atk}/${f.ivs.def}/${f.ivs.hp}`)).size > 1;
  let best = null;
  if (settled.length) { const v = vote(settled.map((f) => f.ivs), (x) => `${x.atk}/${x.def}/${x.hp}`); best = { f: settled.filter((f) => f.ivs.atk === v.atk && f.ivs.def === v.def && f.ivs.hp === v.hp).pop() }; }
  else { const any = frames.filter((f) => f.ivs); if (any.length) best = { f: any[any.length - 1] }; }
  return {
    name: frames[0].name, cp: cpCandidates[0].v, cpCandidates: cpCandidates.map((c) => c.v),
    hp, ivs: best?.f.ivs ?? null, ivConfidence: best?.f.ivConfidence ?? 0, fills: best?.f.fills ?? null, ivsDisagree,
    speciesIds: frames[0].speciesIds, form: frames[0].form, baseName: frames[0].baseName,
    frames: frames.map((f) => ({ frame: f.frame, time: f.time, cp: f.cp, cpText: f.cpText, name: f.nameText, hp: f.hp ? `${f.hp.current}/${f.hp.max}` : null, ivs: f.ivs ? `${f.ivs.atk}/${f.ivs.def}/${f.ivs.hp}` : null, ivConfidence: f.ivConfidence, sharpness: f.sharpness })),
  };
}

/**
 * Merge adjacent rows that are the same Pokémon (same name and CP, HP and IVs not in conflict).
 * Keeps the row with more information. Never merges rows that are not adjacent.
 */
function dedupeAdjacent(rows) {
  const out = [];
  for (const r of rows) {
    const prev = out[out.length - 1];
    if (prev && prev.name === r.name && prev.cp === r.cp && agree(prev.hp, r.hp) && ivsCompatible(prev.ivs, r.ivs, prev.ivConfidence, r.ivConfidence)) {
      const keep = score(r) > score(prev) ? { ...r } : { ...prev };
      keep.hp = prev.hp ?? r.hp; keep.ivs = keep.ivs ?? prev.ivs ?? r.ivs;
      keep.cpCandidates = [...new Set([...(prev.cpCandidates ?? []), ...(r.cpCandidates ?? [])])];
      keep.frames = [...prev.frames, ...r.frames];
      keep.merged = (prev.merged ?? 1) + 1;
      out[out.length - 1] = keep;
    } else out.push({ ...r });
  }
  return out;
}

const agree = (a, b) => a === null || b === null || a === undefined || b === undefined || a === b;
const score = (r) => (r.hp ? 1 : 0) + (r.ivs ? 2 : 0) + r.frames.length / 100;
return { identity, cpSimilar, SETTLED, ivsCompatible, groupRuns, ranked, vote, collapseRun, dedupeAdjacent };
});
__def("src/cpm.js", function () {
// CP multipliers by level (1 to 51 in half steps) and the CP / HP formulas.
// Values are the public game constants; test/cpm.test.js checks them against real exports.
const CPM = {
  1: 0.094, 1.5: 0.1351374318, 2: 0.16639787, 2.5: 0.192650919, 3: 0.21573247, 3.5: 0.2365726613,
  4: 0.25572005, 4.5: 0.2735303812, 5: 0.29024988, 5.5: 0.3060573775, 6: 0.3210876, 6.5: 0.3354450362,
  7: 0.34921268, 7.5: 0.3624577511, 8: 0.3752356, 8.5: 0.387592416, 9: 0.39956728, 9.5: 0.4111935514,
  10: 0.4225, 10.5: 0.4329264091, 11: 0.44310755, 11.5: 0.4530599591, 12: 0.4627984, 12.5: 0.472336093,
  13: 0.48168495, 13.5: 0.4908558003, 14: 0.49985844, 14.5: 0.508701765, 15: 0.51739395, 15.5: 0.5259425113,
  16: 0.5343543, 16.5: 0.5426357375, 17: 0.5507927, 17.5: 0.5588305862, 18: 0.5667545, 18.5: 0.5745691333,
  19: 0.5822789, 19.5: 0.5898879072, 20: 0.5974, 20.5: 0.6048236651, 21: 0.6121573, 21.5: 0.6194041216,
  22: 0.6265671, 22.5: 0.6336491432, 23: 0.64065295, 23.5: 0.6475809666, 24: 0.65443563, 24.5: 0.6612192524,
  25: 0.667934, 25.5: 0.6745818959, 26: 0.6811649, 26.5: 0.6876849038, 27: 0.69414365, 27.5: 0.70054287,
  28: 0.7068842, 28.5: 0.7131691091, 29: 0.7193991, 29.5: 0.7255756136, 30: 0.7317, 30.5: 0.7347410093,
  31: 0.7377695, 31.5: 0.7407855938, 32: 0.74378943, 32.5: 0.7467812109, 33: 0.74976104, 33.5: 0.7527290867,
  34: 0.7556855, 34.5: 0.7586303683, 35: 0.76156384, 35.5: 0.7644860647, 36: 0.76739717, 36.5: 0.7702972656,
  37: 0.7731865, 37.5: 0.7760649616, 38: 0.77893275, 38.5: 0.7817900548, 39: 0.784637, 39.5: 0.7874736075,
  40: 0.7903, 40.5: 0.792803968, 41: 0.79530001, 41.5: 0.797800015, 42: 0.8003, 42.5: 0.802799995,
  43: 0.8053, 43.5: 0.8078, 44: 0.81029999, 44.5: 0.812799985, 45: 0.81529999, 45.5: 0.81779999,
  46: 0.82029999, 46.5: 0.82279999, 47: 0.82529999, 47.5: 0.82779999, 48: 0.83029999, 48.5: 0.83279999,
  49: 0.83529999, 49.5: 0.83779999, 50: 0.84029999, 50.5: 0.84279999, 51: 0.84529999,
};

const LEVELS = Object.keys(CPM).map(Number).sort((a, b) => a - b);

// Lookup by Map: `CPM[12.5]` turns the number into a string key on every call, and the solver calls this
// millions of times on a large box. Same values, same RangeError for a level that has no multiplier.
const CPM_BY_LEVEL = new Map(Object.entries(CPM).map(([k, v]) => [Number(k), v]));

function cpm(level) {
  const v = CPM_BY_LEVEL.get(level);
  if (v === undefined) throw new RangeError(`no CP multiplier for level ${level}`);
  return v;
}

/** CP for base stats {atk, def, hp}, IVs {atk, def, hp} and a level. */
function cpAt(base, ivs, level) {
  const m = cpm(level);
  const cp = Math.floor(((base.atk + ivs.atk) * Math.sqrt(base.def + ivs.def) * Math.sqrt(base.hp + ivs.hp) * m * m) / 10);
  return Math.max(10, cp);
}

/** HP (stamina) for base stats, IVs and a level. */
function hpAt(base, ivs, level) {
  return Math.max(10, Math.floor((base.hp + ivs.hp) * cpm(level)));
}

/** Highest level at or under a CP cap for the given base stats and IVs (null if level 1 is already over). */
function maxLevelUnderCap(base, ivs, cap, maxLevel = 51) {
  let best = null;
  for (const lv of LEVELS) {
    if (lv > maxLevel) break;
    if (cpAt(base, ivs, lv) <= cap) best = lv; else break;
  }
  return best;
}

/** Stat product (attack × defence × stamina, using real not floored values except HP) — the PvP bulk measure. */
function statProduct(base, ivs, level) {
  const m = cpm(level);
  return (base.atk + ivs.atk) * m * (base.def + ivs.def) * m * Math.floor((base.hp + ivs.hp) * m);
}
return { LEVELS, cpm, cpAt, hpAt, maxLevelUnderCap, statProduct };
});
__def("src/extract/solve.js", function () {
const { cpAt, hpAt, LEVELS } = __use("src/cpm.js");
// Given what was read off the screen (species candidates, CP, HP, bar IVs), find the IVs and
// level that reproduce CP and HP. Megas use the Mega form's stats (the fixture confirms Poke
// Genie records the Mega's CP and HP).
//
// The appraisal bars animate from the previous Pokémon's values to this one's when the panel
// changes, so a frame taken mid-animation reads anything between the two. The solver ranks
// candidate IV sets against the read:
//   tier 0  exactly the bars read
//   tier 1  every bar within one unit (a rounding miss on a small frame)
//   tier 2  anything else that fits CP and HP (the read was mid-animation or another panel)



/**
 * @param species  [{ speciesId, baseStats }] candidates the name could be
 * @param cp       read CP (required)
 * @param hp       read HP or null
 * @param ivs      { atk, def, hp } from the bars, or null when the panel was not read
 * @returns { status, solutions: [{ speciesId, ivs, level, hp, tier }], forms } sorted best first;
 *   `forms` lists the species ids that fit equally well (same stats), first one used.
 *   status: 'exact' | 'corrected' (one tier-1 set) | 'ambiguous' (several sets in the best
 *           tier, or nothing near the read) | 'unknown-ivs' (no bars) | 'none'
 */
function solve({ species, cp, hp = null, ivs = null }) {
  if (!cp || !species?.length) return { status: 'none', solutions: [] };
  const fits = [];
  for (const sp of species) {
    for (const c of allCombos()) {
      for (const level of LEVELS) {
        const v = cpAt(sp.baseStats, c, level);
        if (v > cp) break;
        if (v !== cp) continue;
        const h = hpAt(sp.baseStats, c, level);
        if (hp !== null && h !== hp) continue;
        fits.push({ speciesId: sp.speciesId, ivs: c, level, hp: h, tier: ivs ? tierOf(ivs, c) : 3 });
      }
    }
  }
  if (!fits.length) return { status: ivs ? 'none' : 'unknown-ivs', solutions: [] };
  // Ties between forms with the same stats (costume Pikachu, say) go to the plainest id, and are
  // reported so the row can be flagged: the screen name does not say which form it is.
  fits.sort((a, b) => a.tier - b.tier || dist(ivs, a.ivs) - dist(ivs, b.ivs) || a.level - b.level || a.speciesId.length - b.speciesId.length || (a.speciesId < b.speciesId ? -1 : 1));
  const bestTier = fits[0].tier;
  const top = fits.filter((f) => f.tier === bestTier);
  const forms = new Set(top.map((s) => s.speciesId));
  const out = (status) => ({ status, solutions: fits, forms: [...forms] });
  if (!ivs) return out('unknown-ivs');
  const distinct = new Set(top.map((s) => `${s.ivs.atk}/${s.ivs.def}/${s.ivs.hp}`));
  if (distinct.size > 1 && bestTier > 0) return out('ambiguous');
  return out(['exact', 'corrected', 'ambiguous'][bestTier]);
}

function tierOf(read, c) {
  const r = [read.atk, read.def, read.hp], t = [c.atk, c.def, c.hp];
  if (r.every((v, i) => v === t[i])) return 0;
  if (r.every((v, i) => Math.abs(v - t[i]) <= 1)) return 1;
  return 2;
}

function dist(a, b) { return a ? Math.abs(a.atk - b.atk) + Math.abs(a.def - b.def) + Math.abs(a.hp - b.hp) : 0; }

let ALL = null;
function allCombos() {
  if (!ALL) { ALL = []; for (let a = 0; a <= 15; a++) for (let d = 0; d <= 15; d++) for (let h = 0; h <= 15; h++) ALL.push({ atk: a, def: d, hp: h }); }
  return ALL;
}

/** Species candidates for a matched display name: the base stats each id would be checked with. */
function speciesFor(gm, speciesIds) {
  return speciesIds.map((id) => gm.byId.get(id)).filter(Boolean).map((p) => ({ speciesId: p.speciesId, baseStats: p.baseStats, speciesName: p.speciesName }));
}
return { solve, speciesFor };
});
__def("src/cost.js", function () {
// Power-up costs: stardust and candy per half-level step, XL candy from level 40.
// step(level) is the cost of the power-up that starts at `level` and ends at level + 0.5.

function bracket(level, table) {
  for (const [from, to, value] of table) if (level >= from && level <= to) return value;
  throw new RangeError(`no cost entry for level ${level}`);
}

// [fromLevel, toLevel inclusive, value] — each row covers the power-ups starting in that range.
const DUST = [
  [1, 2.5, 200], [3, 4.5, 400], [5, 6.5, 600], [7, 8.5, 800], [9, 10.5, 1000],
  [11, 12.5, 1300], [13, 14.5, 1600], [15, 16.5, 1900], [17, 18.5, 2200], [19, 20.5, 2500],
  [21, 22.5, 3000], [23, 24.5, 3500], [25, 26.5, 4000], [27, 28.5, 4500], [29, 30.5, 5000],
  [31, 32.5, 6000], [33, 34.5, 7000], [35, 36.5, 8000], [37, 38.5, 9000], [39, 40.5, 10000],
  [41, 42.5, 11000], [43, 44.5, 12000], [45, 46.5, 13000], [47, 48.5, 14000], [49, 50.5, 15000],
];
// Fitted against 183 start/target pairs from a Poke Genie export (see test/cpm.test.js).
const CANDY = [
  [1, 10.5, 1], [11, 20.5, 2], [21, 25.5, 3], [26, 30.5, 4], [31, 32.5, 6], [33, 34.5, 8],
  [35, 36.5, 10], [37, 38.5, 12], [39, 39.5, 15],
];
const XL = [
  [40, 41.5, 10], [42, 43.5, 12], [44, 45.5, 15], [46, 47.5, 17], [48, 49.5, 20], [50, 50.5, 0],
];

const SHADOW_MULTIPLIER = 1.2;
const PURIFIED_MULTIPLIER = 0.9;
const LUCKY_DUST_MULTIPLIER = 0.5;

/** Cost of one power-up starting at `level`. */
function step(level) {
  if (level >= 50) return { dust: 0, candy: 0, xl: 0 }; // 50 -> 51 is the Best Buddy boost, not a power-up
  const dust = bracket(level, DUST);
  return level >= 40
    ? { dust, candy: 0, xl: bracket(level, XL) }
    : { dust, candy: bracket(level, CANDY), xl: 0 };
}

/**
 * Total cost to go from `from` to `to` (both half-levels, to > from).
 * flags: { shadow, purified, lucky } apply the standard multipliers.
 * Shadow multiplies dust and candy; purified multiplies dust and candy; lucky halves dust only.
 */
function powerUpCost(from, to, flags = {}) {
  if (to <= from) return { dust: 0, candy: 0, xl: 0, steps: 0 };
  let dust = 0, candy = 0, xl = 0, steps = 0;
  for (let lv = from; lv < to; lv += 0.5) {
    const s = step(lv);
    dust += s.dust; candy += s.candy; xl += s.xl; steps += 1;
  }
  let mult = 1;
  if (flags.shadow) mult *= SHADOW_MULTIPLIER;
  if (flags.purified) mult *= PURIFIED_MULTIPLIER;
  let dustMult = mult;
  if (flags.lucky) dustMult *= LUCKY_DUST_MULTIPLIER;
  return {
    dust: Math.round(dust * dustMult),
    candy: Math.ceil(candy * mult),
    xl: Math.ceil(xl * mult),
    steps,
  };
}

/** Second charged move cost from the game master's thirdMoveCost (stardust); candy is dust / 1000. Shadows pay 1.2×. */
function secondMoveCost(thirdMoveCostDust, flags = {}) {
  const mult = flags.shadow ? SHADOW_MULTIPLIER : flags.purified ? PURIFIED_MULTIPLIER : 1;
  return { dust: Math.round(thirdMoveCostDust * mult), candy: Math.round((thirdMoveCostDust / 1000) * mult) };
}
return { SHADOW_MULTIPLIER, PURIFIED_MULTIPLIER, LUCKY_DUST_MULTIPLIER, step, powerUpCost, secondMoveCost };
});
__def("src/extract/pipeline.js", function () {
const { readFrame } = __use("src/extract/frame.js");
const { displayNames, nameAndForm } = __use("src/extract/names.js");
const { groupRuns, collapseRun, dedupeAdjacent, cpSimilar, ivsCompatible, vote, SETTLED } = __use("src/extract/merge.js");
const { solve, speciesFor } = __use("src/extract/solve.js");
const { step: dustStep } = __use("src/cost.js");
const { cpAt, hpAt, LEVELS } = __use("src/cpm.js");
// The extractor: frames in, roster rows out. Shared by the CLI (frames from ffmpeg PNGs) and the
// web page (frames from a <video> element). Frames arrive through an async iterable so neither
// side has to hold a whole recording in memory.








/**
 * @param frames    async iterable of { index, time, image, label }
 * @param ocr       from createOcr
 * @param gm        indexed game master
 * @param onProgress ({ done, total, found, reading }) after each frame; total may be null
 * @returns { rows, review, readings }
 */
async function extract(frames, { ocr, gm, onProgress = () => {}, total = null }) {
  const names = displayNames(gm);
  const readings = [];
  let done = 0, found = 0, lastKey = null;
  for await (const f of frames) {
    const r = await readFrame(f.image, ocr, names, { frame: f.label ?? f.index, time: f.time });
    readings.push(r);
    done++;
    const key = r.cp && r.name ? `${r.name}|${r.cp}` : null;
    if (key && key !== lastKey) { found++; lastKey = key; }
    onProgress({ done, total, found, reading: r });
  }
  return { ...finish(readings, gm), readings };
}

/**
 * Everything after the frames are read: group, vote, solve, dedupe, flag.
 *
 * Names read without OCR confidence (`nameWeak`, frame.js) are kept apart from the rest. The rows
 * of every Pokémon with a confidently named frame are built from the confident frames alone, by
 * exactly the steps used before weak names were read (group, collapse, dedupe), so a weak frame
 * can neither outvote such a row's CP nor split it. Weak frames then add rows only where no
 * confident row could be theirs (weakRows), and those rows are flagged `name-low-confidence`.
 */
function finish(readings, gm) {
  const named = readings.map((r, i) => (r?.name ? i : -1)).filter((i) => i >= 0);
  // "Nidoran" with a letter stuck to it, next to a Nidorina or Nidorino frame, is that Pokémon's
  // name misread by a letter: unreadable, so it cannot split the run.
  const nidorStray = (r, i) => {
    if (r?.name !== 'Nidoran' || !r.nameAttached) return false;
    const at = named.indexOf(i);
    return [named[at - 1], named[at + 1]].some((j) => j !== undefined && /^Nidorin[ao]$/.test(readings[j].name));
  };
  const strong = readings.map((r, i) => (r?.nameWeak || nidorStray(r, i) ? { ...r, name: null, cp: null, nameWeak: false } : r));
  const runs = groupRuns(strong);
  const at = new Map(strong.map((r, i) => [r, i]));
  const runSpans = runs.map((run) => [at.get(run.frames[0]), at.get(run.frames[run.frames.length - 1])]);
  const strongRows = dedupeAdjacent(runs.map((run, k) => ({ ...collapseRun(run), order: runSpans[k][0] })));
  // Where each row's Pokémon was on screen. dedupeAdjacent can join two runs into one row, whose
  // span is then first frame to last frame; that needs frame labels to find them again, so
  // without unique labels the spans stay those of the runs.
  const labels = new Map();
  let unique = true;
  strong.forEach((r, i) => { const key = r?.frame; if (key === null || key === undefined || labels.has(key)) unique = false; else labels.set(key, i); });
  const spans = unique
    ? strongRows.map((row) => ({ name: row.name, a: labels.get(row.frames[0].frame), b: labels.get(row.frames[row.frames.length - 1].frame) }))
    : runs.map((run, k) => ({ name: run.frames[0].name, a: runSpans[k][0], b: runSpans[k][1] }));
  if (unique) strongRows.forEach((row, k) => { row.order = spans[k].a; });
  const { rows: weak, setAside } = weakRows(readings, spans);
  const collapsed = [...strongRows, ...weak].sort((a, b) => a.order - b.order);
  const { rows, absorbed } = absorbStrays(collapsed.map((row) => resolveRow(row, gm)));
  rows.forEach((r, i) => { r.index = i + 1; });
  // What was on screen and did not become a row is listed, so it is not silently missing: frames
  // that showed a CP but no species name (a nickname, or a garbled read: two frames or more in a
  // row with the same CP, so a single frame caught mid-change is not listed); a named Pokémon whose
  // CP was never read (hidden behind its model), with the CPs its HP and bars allow; and a
  // one-frame row folded into its neighbour.
  const view = strong.map((r, i) => (setAside.has(i) ? { ...readings[i], name: null, nameWeak: false, flags: [...(readings[i].flags ?? []), 'name-unsupported'] } : r));
  const unmatched = [...unnamedEntries(view), ...hiddenEntries(view, runs, gm), ...absorbed];
  const review = rows.filter((r) => r.flags.length).map((r) => ({ index: r.index, name: r.name, cp: r.cp, hp: r.hp, ivs: r.ivs, ivsRead: r.ivsRead, ivsGuess: r.ivsGuess, level: r.level, levelMax: r.levelMax, flags: r.flags, frames: r.frames }));
  return { rows, review, unmatched };
}

/**
 * The CPs a Pokémon could have, from what a model in front of the CP text cannot hide: its HP and
 * its settled bars. Each level whose HP matches gives one CP. `reads` are the partial CP reads
 * (the model usually covers the leading digits, so a read is the tail of the real number).
 * Returns { options, supported, tailOf }: every CP that fits, those a partial read is the tail
 * of, and for each of those the read that supports it.
 */
function cpOptions(species, { hp, ivs, ivConfidence = 1 }, reads = []) {
  if (!hp || !ivs || ivConfidence < SETTLED) return { options: [], supported: [], tailOf: new Map() };
  const options = new Set();
  for (const sp of species) for (const level of LEVELS) if (hpAt(sp.baseStats, ivs, level) === hp) options.add(cpAt(sp.baseStats, ivs, level));
  const tails = reads.filter((r) => r >= 10).map(String);
  const all = [...options].sort((a, b) => a - b);
  const tailOf = new Map();
  for (const cp of all) { const t = tails.find((x) => x.length < String(cp).length && String(cp).endsWith(x)); if (t) tailOf.set(cp, Number(t)); }
  return { options: all, supported: [...tailOf.keys()], tailOf };
}

/**
 * Rows for Pokémon read only with weak names. `spans` are the confident rows' times on screen
 * ({ name, a, b }, in order). A weak frame with a CP:
 * - between the first and last frame of a confident row belongs to that Pokémon's time on
 *   screen. With its name it is dropped (as before weak names were read); with another name
 *   ("Paras" in the middle of a Parasect) it is set aside to be listed as unread;
 * - between two confident rows is dropped when it has the name of the row on either side, since
 *   it may be that Pokémon's first or last frame; otherwise it is a Pokémon no confident frame
 *   accounts for, and such frames are grouped into rows;
 * - before the first confident row or after the last is dropped: a clip is joined to the next
 *   by matching its last rows to the next clip's first rows (batch.js), and a row that only one
 *   of the two clips has there would hide the overlap. A clip with no confident row at all keeps
 *   its weak rows.
 * Returns { rows: collapsed rows with nameWeak and order, setAside: Set of reading indices }.
 */
function weakRows(readings, spans) {
  const setAside = new Set();
  const gaps = new Map(); // index of the confident row after the gap -> weak readings in it
  readings.forEach((r, i) => {
    if (!r?.nameWeak || !r.name || !r.cp) return;
    const inside = spans.find((s) => i > s.a && i < s.b);
    if (inside) { if (r.name !== inside.name) setAside.add(i); return; }
    let next = spans.findIndex((s) => s.a > i);
    if (next < 0) next = spans.length;
    if (spans.length && (next === 0 || next === spans.length)) return;
    if (r.name === spans[next - 1]?.name || r.name === spans[next]?.name) return;
    if (!gaps.has(next)) gaps.set(next, []);
    gaps.get(next).push({ r, i });
  });
  const rows = [];
  for (const members of gaps.values()) {
    const first = new Map(members.map(({ r, i }) => [r, i]));
    for (const run of groupRuns(members.map(({ r }) => r))) rows.push({ ...collapseRun(run), nameWeak: true, order: first.get(run.frames[0]) });
  }
  return { rows, setAside };
}

function resolveRow(row, gm) {
  const species = speciesFor(gm, row.speciesIds ?? []);
  const flags = [];
  // The CP: the first candidate read (ranked by how many frames read it) that the solver can
  // reconcile with the HP and bars; failing that, the most-read one.
  const candidates = row.cpCandidates ?? [row.cp];
  let cp = row.cp, result = null;
  for (const candidate of candidates) {
    const r = solve({ species, cp: candidate, hp: row.hp, ivs: row.ivs });
    if (r.solutions.length && (!row.ivs || r.solutions[0].tier <= 1)) { cp = candidate; result = r; break; }
  }
  if (result) { if (cp !== row.cp) flags.push(`cp-chosen-${cp}-over-${row.cp}`); }
  else {
    // No read fits. When the model covered the leading digits, the reads are the tail of the real
    // CP: work the CP out from the HP and the settled bars, and take it when exactly one such CP
    // ends in a read and no read at all is as long as it (a full-length read that does not fit
    // means misread bars, not a hidden digit). The row stays flagged for a check in the game.
    const { supported, tailOf } = cpOptions(species, row, candidates);
    if (supported.length === 1 && !candidates.some((c) => String(c).length >= String(supported[0]).length)) { cp = supported[0]; flags.push(`cp-recovered:${cp}-from-${tailOf.get(cp)}`); }
    result = solve({ species, cp, hp: row.hp, ivs: row.ivs });
  }
  let ivs = row.ivs, level = null, levelMax = null, speciesId = species[0]?.speciesId ?? null, hp = row.hp;
  const s = result.solutions[0];
  const take = () => { ivs = s.ivs; level = s.level; levelMax = s.level; speciesId = s.speciesId; if (hp === null) { hp = s.hp; flags.push('hp-computed'); } };
  switch (result.status) {
    case 'exact': {
      take();
      const levels = new Set(result.solutions.filter((x) => x.tier === 0).map((x) => x.level));
      if (levels.size > 1) { level = Math.min(...levels); levelMax = Math.max(...levels); flags.push(`level-ambiguous:${[...levels].join('|')}`); }
      break;
    }
    case 'corrected': take(); flags.push(`ivs-corrected-from-${row.ivs.atk}/${row.ivs.def}/${row.ivs.hp}`); break;
    case 'ambiguous': {
      // Several IV sets fit: export none of them (the advisor must not treat a guess as fact) and
      // give the level range they span; the nearest guess stays in review.json.
      const top = result.solutions.filter((x) => x.tier === s.tier);
      ivs = null; level = Math.min(...top.map((x) => x.level)); levelMax = Math.max(...top.map((x) => x.level)); speciesId = s.speciesId;
      if (hp === null) { hp = s.hp; flags.push('hp-computed'); }
      flags.push(`ambiguous-ivs:${top.length}-fit`);
      break;
    }
    case 'unknown-ivs': {
      ivs = null;
      if (s) speciesId = s.speciesId; // the species that fits, not just the first the name could be
      const levels = result.solutions.map((x) => x.level);
      if (levels.length) { level = Math.min(...levels); levelMax = Math.max(...levels); }
      flags.push('ivs-unread');
      break;
    }
    default: ivs = null; flags.push('no-level-fits');
  }
  if (result.forms?.length > 1) flags.push(`form-ambiguous:${result.forms.join('|')}`);
  if (row.ivsDisagree) flags.push('ivs-disagree');
  // Every frame's name was read without OCR confidence: it can be a longer name cut short by an
  // overlay ("Paras" from "Parasect"), so the row is for a check in the game.
  if (row.nameWeak) flags.push('name-low-confidence');
  // The screen cannot tell Nidoran♀ from Nidoran♂ here (the symbol is not read): the sex is the
  // one whose stats fit the CP, HP and bars, so a misread CP could also pick the wrong one.
  if (row.name === 'Nidoran') flags.push('sex-from-stats');
  if (hp === null) flags.push('hp-unread');
  if (row.ivs && row.ivConfidence < SETTLED) flags.push('bars-unsettled');
  // Name and form as Poke Genie writes them, from the species the solver settled on (the screen
  // shows "Zamazenta" for both the Hero and the Crowned Shield form).
  const sp = speciesId ? gm.byId.get(speciesId) : null;
  const nf = sp ? nameAndForm(sp) : { name: row.baseName ?? row.name, form: row.form ?? '' };
  return {
    index: null, name: nf.name, display: row.name, form: nf.form, speciesId, dex: sp?.dex ?? null,
    cp, hp, ivs, ivsRead: row.ivs, ivsGuess: ivs === null && s ? s.ivs : null, level, levelMax,
    dust: level ? dustStep(level).dust : null,
    solveStatus: result.status, flags, frames: row.frames, merged: row.merged ?? 1,
  };
}

/**
 * Frames that showed a CP but no species name, as entries for `unmatched`: one per stretch of
 * two or more such frames in a row whose CPs agree, or of any length when the name was read
 * without confidence and set aside (weakRows). { frame, cp, nameText, hp: null, frames, reason }.
 */
function unnamedEntries(readings) {
  const out = [];
  let cur = null;
  const close = () => { if (cur && (cur.frames >= 2 || cur.setAside)) out.push({ frame: cur.frame, cp: vote(cur.cps), nameText: vote(cur.texts) ?? '', hp: null, frames: cur.frames, reason: 'name-not-read' }); cur = null; };
  for (const r of readings) {
    if (!r.cp || r.name) { close(); continue; }
    const setAside = Boolean(r.flags?.includes('name-unsupported'));
    if (cur && cur.cps.some((c) => cpSimilar(c, r.cp))) { cur.cps.push(r.cp); cur.texts.push(r.nameText || null); cur.frames++; cur.setAside ||= setAside; }
    else { close(); cur = { frame: r.frame, cps: [r.cp], texts: [r.nameText || null], frames: 1, setAside }; }
  }
  close();
  return out;
}

/**
 * Pokémon that were on screen with a name but no CP on any frame (the model covered it), as
 * entries for `unmatched`: name, HP, settled bars and the CPs those allow, for a check in the
 * game. Such frames never join a run (rows are built exactly as if they were unreadable); a
 * stretch of them is one entry, unless it sits right beside a run of the same Pokémon (same name,
 * HP not different, bars not contradicting, no unreadable frame between), which is that Pokémon
 * with its model in front of the CP for a moment.
 */
function hiddenEntries(readings, runs, gm) {
  const runOf = new Map();
  for (const run of runs) for (const f of run.frames) runOf.set(f, run);
  const settledIvs = (frames) => vote(frames.filter((f) => f.ivs && f.ivConfidence >= SETTLED).map((f) => f.ivs), (x) => `${x.atk}/${x.def}/${x.hp}`);
  const stretches = [];
  let cur = null, prevRun = null, gap = false;
  for (const r of readings) {
    const run = runOf.get(r);
    if (run) {
      if (cur) { cur.next = run; cur.gapAfter = gap; cur = null; }
      prevRun = run; gap = false;
    } else if (r.name && !r.cp) {
      const hp = r.hp?.max ?? null;
      const ivs = r.ivs && r.ivConfidence >= SETTLED ? r.ivs : null;
      const same = cur && cur.name === r.name && (cur.hp === null || hp === null || cur.hp === hp) && (!gap || ivsCompatible(settledIvs(cur.frames), ivs));
      if (same) { cur.frames.push(r); cur.hp ??= hp; }
      else { cur = { name: r.name, hp, frames: [r], prev: prevRun, gapBefore: gap || cur !== null, next: null, gapAfter: true }; stretches.push(cur); }
      gap = false;
    } else gap = true;
  }
  const beside = (s, run, gapBetween) => run && !gapBetween && run.frames[0].name === s.name && (s.hp === null || !run.hp || run.hp.max === s.hp) && ivsCompatible(run.ivs, settledIvs(s.frames));
  // One or two frames with no HP read are a card caught sliding in or out, not a Pokémon to list.
  const substantial = (s) => s.hp !== null || s.frames.length >= 3;
  return stretches.filter((s) => substantial(s) && !beside(s, s.prev, s.gapBefore) && !beside(s, s.next, s.gapAfter)).map((s) => {
    const ivs = settledIvs(s.frames);
    return {
      frame: s.frames[0].frame, cp: null, name: s.name, nameText: s.frames[0].nameText, hp: s.hp, ivs,
      cpOptions: cpOptions(speciesFor(gm, s.frames[0].speciesIds ?? []), { hp: s.hp, ivs }).options, frames: s.frames.length, reason: 'cp-not-read',
    };
  });
}

/**
 * A one-frame row with no HP and no settled bars that did not solve, next to a row of the same
 * Pokémon with a similar CP, is almost always that Pokémon caught on the frame before its screen
 * settled (one digit misread, HP not yet drawn). Its frame goes to the neighbour, and because it
 * could be a Pokémon of its own it is also listed in `unmatched`.
 * Returns { rows, absorbed }.
 */
function absorbStrays(rows) {
  const out = [], absorbed = [];
  const bare = (r) => (r.flags.includes('hp-computed') || r.flags.includes('hp-unread')) && (!r.ivsRead || r.flags.includes('bars-unsettled'));
  const stray = (r, other) => r.frames.length === 1 && bare(r) && r.solveStatus !== 'exact' && other && other.frames.length > 1 && other.display === r.display && cpSimilar(r.cp, other.cp);
  const note = (r, other) => absorbed.push({ frame: r.frames[0].frame, cp: r.cp, name: r.display, nameText: r.frames[0].name, hp: null, reason: 'absorbed', into: other.cp });
  for (let i = 0; i < rows.length; i++) {
    const r = rows[i], prev = out[out.length - 1], next = rows[i + 1];
    if (stray(r, prev)) { note(r, prev); prev.frames = [...prev.frames, ...r.frames]; continue; }
    if (stray(r, next)) { note(r, next); next.frames = [...r.frames, ...next.frames]; continue; }
    out.push(r);
  }
  return { rows: out, absorbed };
}

/** Poke Genie's column layout, so src/import/pokegenie.js reads the result back. */
const POKEGENIE_COLUMNS = ['Index', 'Name', 'Form', 'Pokemon Number', 'Gender', 'CP', 'HP', 'Atk IV', 'Def IV', 'Sta IV', 'IV Avg', 'Level Min', 'Level Max', 'Quick Move', 'Charge Move', 'Charge Move 2', 'Scan Date', 'Original Scan Date', 'Catch Date', 'Weight', 'Height', 'Lucky', 'Shadow/Purified', 'Favorite', 'Dust', 'Rank % (G)', 'Rank # (G)', 'Stat Prod (G)', 'Dust Cost (G)', 'Candy Cost (G)', 'Name (G)', 'Form (G)', 'Sha/Pur (G)', 'Rank % (U)', 'Rank # (U)', 'Stat Prod (U)', 'Dust Cost (U)', 'Candy Cost (U)', 'Name (U)', 'Form (U)', 'Sha/Pur (U)', 'Rank % (L)', 'Rank # (L)', 'Stat Prod (L)', 'Dust Cost (L)', 'Candy Cost (L)', 'Name (L)', 'Form (L)', 'Sha/Pur (L)', 'Marked for PvP use'];

function toPokeGenieCsv(rows, { scanDate = new Date() } = {}) {
  const date = `${scanDate.getFullYear()}-${String(scanDate.getMonth() + 1).padStart(2, '0')}-${String(scanDate.getDate()).padStart(2, '0')} ${String(scanDate.getHours()).padStart(2, '0')}:${String(scanDate.getMinutes()).padStart(2, '0')}`;
  const q = (v) => { const s = v === null || v === undefined ? '' : String(v); return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s; };
  const lines = [POKEGENIE_COLUMNS.join(',')];
  for (const r of rows) {
    const rec = {
      Index: r.index, Name: r.name, Form: r.form, 'Pokemon Number': r.dex ?? '', Gender: '', CP: r.cp, HP: r.hp ?? '',
      'Atk IV': r.ivs?.atk ?? '', 'Def IV': r.ivs?.def ?? '', 'Sta IV': r.ivs?.hp ?? '',
      'IV Avg': r.ivs ? ((r.ivs.atk + r.ivs.def + r.ivs.hp) / 45 * 100).toFixed(1) : '',
      'Level Min': r.level !== null ? r.level.toFixed(1) : '', 'Level Max': r.levelMax !== null ? r.levelMax.toFixed(1) : '',
      // Lucky and Favourite are not read from the screen: left blank, not asserted as 0. Shadow/
      // Purified is only known when a batch merge marked the row from a Shadow-filtered pass
      // (1 shadow, 2 purified); otherwise it is unread, so blank rather than 0.
      'Scan Date': date, 'Original Scan Date': date, Lucky: '', 'Shadow/Purified': r.shadow === 1 || r.shadow === 2 ? r.shadow : '', Favorite: '', Dust: r.dust ?? '',
    };
    lines.push(POKEGENIE_COLUMNS.map((c) => q(rec[c] ?? '')).join(','));
  }
  return lines.join('\n') + '\n';
}
return { extract, finish, cpOptions, POKEGENIE_COLUMNS, toPokeGenieCsv };
});
__def("src/extract/batch.js", function () {
const { ivsCompatible } = __use("src/extract/merge.js");
// Merge several clips of one account into one roster. Pure and browser-safe (no node: imports):
// the batch CLI and the extractor page both call mergeClips with rows from extract().
//
// A box is recorded as several clips (a phone recording is restarted, or a Shadow-filtered pass
// is recorded separately). Within a kind of pass the clips are joined in order, dropping the
// Pokémon repeated where one clip ended and the next began; the Shadow/Purified passes are then
// reconciled into the normal pass by marking the rows they match.
//
// Rows here are what resolveRow() in pipeline.js produces: they carry `ivs` (null when unread or
// ambiguous), `hp`, `flags` and `solveStatus`, but no ivConfidence, so "could these two rows be
// the same Pokémon" is judged from the flags: bars that were never settled, corrected or
// disagreeing IVs, and a computed HP are guesses and do not count as a conflict.



/** Which pass a clip is, from its file name (directories are ignored). */
function passKind(filename) {
  const base = String(filename).split(/[\\/]/).pop().toLowerCase();
  if (base.includes('shadow')) return 'shadow';
  if (base.includes('purified')) return 'purified';
  return 'normal';
}

/** String compare where digit runs compare as numbers (clip2 before clip10), ignoring case. */
function naturalCompare(a, b) {
  const x = String(a).toLowerCase().match(/\d+|\D+/g) ?? [];
  const y = String(b).toLowerCase().match(/\d+|\D+/g) ?? [];
  for (let i = 0; i < Math.min(x.length, y.length); i++) {
    if (x[i] === y[i]) continue;
    const nx = /^\d/.test(x[i]), ny = /^\d/.test(y[i]);
    if (nx && ny) { const d = Number(x[i]) - Number(y[i]); if (d) return d; if (x[i].length !== y[i].length) return x[i].length - y[i].length; }
    else return x[i] < y[i] ? -1 : 1;
  }
  return x.length - y.length;
}

/** Sort `[{ name, mtimeMs }]` by name (natural), or by modified time then name. Returns a new array. */
function orderClips(clips, { order = 'name' } = {}) {
  const byName = (a, b) => naturalCompare(a.name, b.name);
  return [...clips].sort(order === 'mtime' ? (a, b) => (a.mtimeMs - b.mtimeMs) || byName(a, b) : byName);
}

const has = (v) => v !== null && v !== undefined;
const flagged = (r, f) => (r.flags ?? []).some((x) => x === f || x.startsWith(`${f}-`) || x.startsWith(`${f}:`));

/** IVs on this row are a guess (bars unsettled, corrected, disagreeing), so they cannot conflict. */
const ivsLenient = (r) => flagged(r, 'bars-unsettled') || flagged(r, 'ivs-corrected-from') || flagged(r, 'ivs-disagree') || r.solveStatus === 'corrected';
/** HP on this row was computed from the solved level, not read. */
const hpLenient = (r) => flagged(r, 'hp-computed');

/** Could two extractor rows be the same Pokémon? Guessed HP or IVs, and a missing HP, do not conflict. */
function sameMon(a, b) {
  if (a.name !== b.name || (a.form ?? '') !== (b.form ?? '') || a.cp !== b.cp) return false;
  if (has(a.hp) && has(b.hp) && !hpLenient(a) && !hpLenient(b) && a.hp !== b.hp) return false;
  if (a.ivs && b.ivs && !ivsLenient(a) && !ivsLenient(b) && !ivsCompatible(a.ivs, b.ivs, a.ivConfidence ?? 1, b.ivConfidence ?? 1)) return false;
  return true;
}

/** A match that rests on less than both rows' HP and IVs being read and equal. */
function weakPair(a, b) {
  return !has(a.hp) || !has(b.hp) || !a.ivs || !b.ivs || ivsLenient(a) || ivsLenient(b) || hpLenient(a) || hpLenient(b);
}

/**
 * How the end of `tailRows` overlaps the start of `headRows`. `k` is the SMALLEST k <= max such
 * that the last k of the tail match the first k of the head pairwise (for distinct Pokémon only
 * the true overlap is consistent; for a run of identical rows the smallest k drops the fewest,
 * so no Pokémon is lost). `weak` when more than one k is consistent or any matched pair is weak.
 */
function overlapInfo(tailRows, headRows, { max = 10 } = {}) {
  const consistent = [];
  for (let k = 1; k <= Math.min(max, tailRows.length, headRows.length); k++) {
    let ok = true;
    for (let i = 0; i < k && ok; i++) ok = sameMon(tailRows[tailRows.length - k + i], headRows[i]);
    if (ok) consistent.push(k);
  }
  if (!consistent.length) return { k: 0, weak: false, ks: [] };
  const k = consistent[0];
  let weak = consistent.length > 1;
  for (let i = 0; i < k; i++) weak ||= weakPair(tailRows[tailRows.length - k + i], headRows[i]);
  return { k, weak, ks: consistent };
}

/**
 * When several overlaps fit, the smallest is dropped but rows up to the largest may be repeats:
 * head rows k..largest-1 are Pokémon that might be listed twice, so they and the tail rows they
 * would repeat are flagged. `ks` lists every consistent overlap length.
 */
const overlapLength = (tailRows, headRows, opts) => overlapInfo(tailRows, headRows, opts).k;

// Settled IVs beat a lenient guess whatever the frame count, then any HP, then frames.
const richness = (r) => [r.ivs ? (ivsLenient(r) ? 1 : 2) : 0, has(r.hp) ? 1 : 0, r.frames?.length ?? 0];
const richer = (a, b) => { const x = richness(a), y = richness(b); for (let i = 0; i < 3; i++) if (x[i] !== y[i]) return x[i] > y[i]; return false; };

/**
 * One row standing for the same Pokémon seen twice: the fuller row (IVs, then HP, then frames),
 * frames and flags unioned, and flags that the other row's data has made stale removed.
 */
function combine(a, b) {
  const bFuller = richer(b, a);
  const keep = { ...(bFuller ? b : a) }, other = bFuller ? a : b;
  // The IV reliability of the row whose IVs are kept decides whether the other row's doubts apply.
  const ivsGuessed = ivsLenient(keep.ivs || !other.ivs ? keep : other);
  // HP: a read beats a computed one, and any HP beats none. Replacing a computed HP with a
  // different read one leaves IVs and level solved for the old HP, so that is flagged, not hidden.
  let computed = hpLenient(keep), mismatch = null;
  if (has(other.hp) && (!has(keep.hp) || (computed && !hpLenient(other)))) {
    if (has(keep.hp) && keep.hp !== other.hp) mismatch = `hp-mismatch:${keep.hp}/${other.hp}`;
    keep.hp = other.hp; computed = hpLenient(other);
  }
  if (!keep.ivs && other.ivs) keep.ivs = other.ivs;
  const flags = new Set([...(a.flags ?? []), ...(b.flags ?? [])]);
  // no-level-fits stays only when the kept row itself carried it, or the HP swap disagreed: a
  // discarded row's misread does not condemn a row whose own read solved.
  if (!(keep.flags ?? []).includes('no-level-fits') && !mismatch) flags.delete('no-level-fits');
  if (keep.ivs) for (const f of flags) if (f.startsWith('ambiguous-ivs') || f === 'ivs-unread') flags.delete(f);
  if (keep.ivs && !ivsGuessed) for (const f of flags) if (f === 'bars-unsettled' || f === 'ivs-disagree' || f.startsWith('ivs-corrected-from-')) flags.delete(f);
  if (has(keep.hp)) flags.delete('hp-unread');
  if (has(keep.hp) && computed) flags.add('hp-computed'); else flags.delete('hp-computed');
  if (mismatch) flags.add(mismatch);
  keep.frames = [...(a.frames ?? []), ...(b.frames ?? [])];
  keep.flags = [...flags];
  return keep;
}

const nameCp = (r) => ({ name: r.display ?? r.name, cp: r.cp });

/**
 * @param clips ordered `[{ name, kind, rows, unmatched = [] }]`
 * @returns { rows, review, unmatched, boundaries, reconciled, clips }
 */
function mergeClips(clips, { maxOverlap = 10 } = {}) {
  const tagged = clips.map((c) => ({
    ...c,
    rows: c.rows.map((r) => ({ ...r, clip: c.name, flags: [...(r.flags ?? [])], frames: (r.frames ?? []).map((f) => ({ ...f, clip: c.name })) })),
  }));

  const boundaries = [];
  const joinKind = (kind) => {
    const out = [];
    for (const c of tagged.filter((x) => x.kind === kind)) {
      let rows = c.rows;
      if (out.length && rows.length) {
        const { k, weak, ks } = overlapInfo(out, rows, { max: maxOverlap });
        // The tail row may itself belong to an earlier clip (a clip that was wholly overlap).
        const before = out[out.length - 1].clip;
        if (!k) {
          // Restarting on the last Pokémon seen should always overlap, so nothing matching
          // means a misread at the join and probably a Pokémon listed twice.
          boundaries.push({ before, after: c.name, dropped: 0, unmatched: true, tail: nameCp(out[out.length - 1]), head: nameCp(rows[0]) });
        } else {
          const largest = ks[ks.length - 1];
          const droppedRows = rows.slice(0, k).map(nameCp);
          const mark = (r) => { if (!r.flags.includes('boundary-weak')) r.flags.push('boundary-weak'); };
          for (let i = 0; i < k; i++) {
            const at = out.length - k + i, clipOf = out[at].clip;
            out[at] = combine(out[at], rows[i]);
            out[at].clip = clipOf;
            if (weak) mark(out[at]);
          }
          const maybeRepeated = rows.slice(k, largest).map(nameCp);
          if (ks.length > 1) {
            for (const r of rows.slice(k, largest)) mark(r);
            for (const r of out.slice(out.length - largest)) mark(r);
          }
          boundaries.push({ before, after: c.name, dropped: k, weak, droppedRows, alternatives: ks, maybeRepeated });
          rows = rows.slice(k);
        }
      }
      out.push(...rows);
    }
    return out;
  };

  const merged = joinKind('normal');
  const reconciled = { matched: 0, appended: 0, ambiguous: 0, weak: 0 };
  const strong = (s, r) => !weakPair(s, r) && s.hp === r.hp && s.ivs.atk === r.ivs.atk && s.ivs.def === r.ivs.def && s.ivs.hp === r.ivs.hp;
  for (const [kind, mark] of [['shadow', 1], ['purified', 2]]) {
    for (const s of joinKind(kind)) {
      s.shadow = mark;
      const candidates = merged.filter((r) => !r.shadow && sameMon(s, r));
      if (!candidates.length) { merged.push(s); reconciled.appended++; continue; }
      const strongOnes = candidates.filter((r) => strong(s, r));
      const pool = strongOnes.length ? strongOnes : candidates;
      const r = pool[0], at = merged.indexOf(r);
      const isWeak = !strong(s, r), isAmbiguous = pool.length > 1;
      const m = combine(r, s);
      m.clip = r.clip; m.shadow = mark;
      if (isAmbiguous && !m.flags.includes('shadow-match-ambiguous')) m.flags.push('shadow-match-ambiguous');
      if (isWeak && !m.flags.includes('shadow-match-weak')) m.flags.push('shadow-match-weak');
      merged[at] = m;
      if (isAmbiguous) reconciled.ambiguous++;
      if (isWeak) reconciled.weak++;
      if (!isAmbiguous && !isWeak) reconciled.matched++;
    }
  }

  merged.forEach((r, i) => { r.index = i + 1; });
  const review = merged.filter((r) => r.flags.length).map((r) => ({ index: r.index, name: r.name, cp: r.cp, hp: r.hp, ivs: r.ivs, ivsRead: r.ivsRead, ivsGuess: r.ivsGuess, level: r.level, levelMax: r.levelMax, flags: r.flags, frames: r.frames, clip: r.clip, shadow: r.shadow }));
  const unmatched = tagged.flatMap((c) => (c.unmatched ?? []).map((u) => ({ ...u, clip: c.name })));
  return {
    rows: merged, review, unmatched, boundaries, reconciled,
    clips: tagged.map((c) => ({ name: c.name, kind: c.kind, rows: c.rows.length, flagged: merged.filter((r) => r.clip === c.name && r.flags.length).length })),
  };
}
return { passKind, naturalCompare, orderClips, ivsLenient, hpLenient, sameMon, weakPair, overlapInfo, overlapLength, combine, mergeClips };
});
__def("src/gamemaster.js", function () {
/** Index PvPoke's game master JSON for lookups. Node code loads the file via src/node/load.js; the browser fetches it. */
function indexGamemaster(gm) {
  const byId = new Map();
  const byTokens = new Map();      // sorted normalised tokens of speciesName -> speciesId
  const byDex = new Map();         // dex -> [species]
  const moves = new Map(gm.moves.map((m) => [m.moveId, m]));
  for (const p of gm.pokemon) {
    byId.set(p.speciesId, p);
    byTokens.set(tokenKey(p.speciesName), p.speciesId);
    if (!byDex.has(p.dex)) byDex.set(p.dex, []);
    byDex.get(p.dex).push(p);
  }
  return { raw: gm, byId, byTokens, byDex, moves, timestamp: gm.timestamp };
}

// Words that do not identify a species or form and can be dropped when matching names.
const NOISE = new Set(['forme', 'form', 'unovan', 'the', 'regular', 'standard', 'dynamax', 'gigantamax', 'gmax', 'g', 'max']);
const DEFAULT_FORMS = ['ordinary', 'altered', 'incarnate', 'land', 'confined', 'standard', 'average', 'baile', 'aria', 'normal'];
const FORM_ALIASES = {
  galar: 'galarian', alola: 'alolan', hisui: 'hisuian', paldea: 'paldean',
  '10%': '10', '50%': '50', 'pa\'u': 'pau', 'pau': 'pau',
};

function tokenKey(name) {
  const tokens = String(name)
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')   // strip accents: Flabébé -> flabebe
    .replace(/♀/g, ' female').replace(/♂/g, ' male')
    .toLowerCase()
    .replace(/[()]/g, ' ')
    .replace(/[-_]/g, ' ')
    .replace(/[^a-z0-9%'.\s]/g, '')
    .split(/\s+/)
    .filter(Boolean)
    .map((t) => FORM_ALIASES[t] ?? t)
    .map((t) => t.replace(/[.']/g, ''))
    .filter((t) => !NOISE.has(t));
  return tokens.sort().join(' ');
}

/**
 * Resolve a display name plus optional form and flags to a game-master speciesId.
 * Accepts tier-list style names ("Shadow Rhyperior", "Mega Charizard Y", "Crowned Shield Zamazenta")
 * and Poke Genie style (name "Charizard", form "Mega Y", shadow flag).
 * Returns { speciesId, species, flags: {shadow, mega, max} } or null.
 */
function resolveSpecies(index, name, { form = '', shadow = false } = {}) {
  const flags = { shadow, mega: false, max: false, megaForm: null };
  // A Poke Genie scan taken while Mega-evolved writes the Mega as the form; the Pokémon is the base species.
  if (/\b(mega|primal)\b/i.test(form)) { flags.mega = true; flags.megaForm = form; form = ''; }
  let text = `${name} ${form}`;
  const lower = text.toLowerCase();
  if (/\b(dynamax|gigantamax|g-max|gmax)\b/.test(lower)) flags.max = true;
  if (/\bmega\b|\bprimal\b/.test(lower)) flags.mega = true;
  if (/\bshadow\b/.test(lower)) flags.shadow = true;
  if (form.toLowerCase() === 'normal') text = name;

  const tryKeys = [];
  const base = tokenKey(text);
  tryKeys.push(flags.shadow && !/\bshadow\b/.test(lower) ? `${base} shadow` : base);
  // Poke Genie writes the Mega form as the Pokémon's form; a scan of a Mega is really the base Pokémon.
  tryKeys.push(tokenKey(text.replace(/\bmega( [xy])?\b/gi, '').replace(/\bprimal\b/gi, '')));
  tryKeys.push(tokenKey(name));
  for (const key of tryKeys) {
    const id = index.byTokens.get(key);
    if (id) return { speciesId: id, species: index.byId.get(id), flags };
    // Species whose plain name is a specific form in the game master (Keldeo -> Ordinary, Giratina -> Altered ...).
    for (const df of DEFAULT_FORMS) {
      const id2 = index.byTokens.get([...key.split(' '), df].sort().join(' '));
      if (id2) return { speciesId: id2, species: index.byId.get(id2), flags };
    }
  }
  // A Shadow that the game master does not list yet (unreleased): fall back to the regular form, flagged.
  if (flags.shadow) {
    const plain = resolveSpecies(index, name.replace(/\bshadow\b/gi, ''), { form });
    if (plain) return { ...plain, flags: { ...plain.flags, shadow: true, unreleasedShadow: true } };
  }
  // Fallback: Poke Genie sometimes writes a form the game master names differently; try each species with the same first token.
  const first = tokenKey(name).split(' ').sort((a, b) => b.length - a.length)[0];
  const candidates = [...index.byId.values()].filter((p) => tokenKey(p.speciesName).split(' ').includes(first));
  if (candidates.length === 1) return { speciesId: candidates[0].speciesId, species: candidates[0], flags };
  return null;
}

/** All speciesIds reachable by evolution from a species (excluding itself), following the game master's family links. */
function evolutionsOf(index, speciesId) {
  const out = [];
  const seen = new Set([speciesId]);
  const stack = [speciesId];
  while (stack.length) {
    const p = index.byId.get(stack.pop());
    for (const next of p?.family?.evolutions ?? []) {
      if (!seen.has(next)) { seen.add(next); out.push(next); stack.push(next); }
    }
  }
  return out;
}

// Form changes that are projects rather than evolutions: energy, cells or fusion turn the left id into the right ones.
const FORM_CHANGES = {
  zamazenta_hero: ['zamazenta_crowned_shield'],
  zacian_hero: ['zacian_crowned_sword'],
  zygarde_10: ['zygarde_50', 'zygarde_complete'],
  zygarde_50: ['zygarde_complete'],
  kyurem: ['kyurem_white', 'kyurem_black'],
  necrozma: ['necrozma_dawn_wings', 'necrozma_dusk_mane'],
  hoopa_confined: ['hoopa_unbound'],
  shaymin_land: ['shaymin_sky'],
};

/** Ids reachable by a form change (energy, cells, fusion) from a species, excluding itself. */
function formChangesOf(index, speciesId) {
  const out = [];
  const stack = [speciesId];
  while (stack.length) {
    for (const next of FORM_CHANGES[stack.pop()] ?? []) if (!out.includes(next) && index.byId.has(next)) { out.push(next); stack.push(next); }
  }
  return out;
}

/** The base (non-shadow, non-mega) speciesId for any variant, e.g. rhyperior_shadow -> rhyperior, charizard_mega_y -> charizard. */
function baseSpeciesId(index, speciesId) {
  let id = speciesId.replace(/_shadow$/, '');
  if (!index.byId.has(id)) id = speciesId;
  const m = id.match(/^(.*)_(mega(?:_[xy])?|primal)$/);
  if (m && index.byId.has(m[1])) id = m[1];
  return id;
}

function shadowIdOf(index, speciesId) {
  const id = `${baseSpeciesId(index, speciesId)}_shadow`;
  return index.byId.has(id) ? id : null;
}

/** Mega/Primal variant ids of a base species. */
function megaIdsOf(index, speciesId) {
  const base = baseSpeciesId(index, speciesId);
  return ['_mega', '_mega_x', '_mega_y', '_primal'].map((s) => base + s).filter((id) => index.byId.has(id));
}
return { indexGamemaster, tokenKey, resolveSpecies, evolutionsOf, FORM_CHANGES, formChangesOf, baseSpeciesId, shadowIdOf, megaIdsOf };
});
__def("src/data.js", function () {
// Pure indexers for the two generated data files (browser-safe; Node loaders live in src/node/load.js).
function indexTiers(t) {
  const bySpecies = new Map();
  for (const e of t.entries) { if (!bySpecies.has(e.speciesId)) bySpecies.set(e.speciesId, []); bySpecies.get(e.speciesId).push(e); }
  return { ...t, bySpecies };
}

function indexRankings(r) {
  const byLeague = {};
  for (const [league, rows] of Object.entries(r.leagues)) byLeague[league] = new Map(rows.map((x) => [x.speciesId, x]));
  return { ...r, byLeague };
}
return { indexTiers, indexRankings };
});
__def("src/advise.js", function () {
const { resolveSpecies, evolutionsOf, formChangesOf, megaIdsOf, baseSpeciesId, FORM_CHANGES } = __use("src/gamemaster.js");
const { powerUpCost, secondMoveCost } = __use("src/cost.js");
const { cpAt } = __use("src/cpm.js");
// The advisor: turns an imported box plus the tier tables and PvP rankings into ranked builds, gaps and hygiene.




const AREA_LABEL = { raids: 'Raids', rocket: 'Rocket', gym: 'Gym', gl: 'GL', ul: 'UL', ml: 'ML', max: 'Max' };
const TIER_W = { S: 3, A: 2, B: 1 };
// How much a hit in each area is worth relative to a raid hit. Gym is shallow; Max hits need a Dynamax-capable copy.
const AREA_W = { raids: 1, gl: 1, ul: 1, ml: 1, rocket: 0.6, max: 0.6, gym: 0.35 };
// PvPoke overall score at or above which a species counts as PvP-relevant even if no tier table names it.
const PVP_SCORE = { gl: 88, ul: 88, ml: 88 };
// Target level per area for costing (PvP uses the export's own per-league cost when available).
const TARGET_LEVEL = { raids: 35, rocket: 30, gym: 30, max: 30, ml: 50, gl: 30, ul: 40 };

// Evolution candy: the game master does not carry it. Defaults by position in the family plus known exceptions.
const EVOLVE_CANDY_OVERRIDES = {
  swablu: 400, magikarp: 400, wailmer: 400, meltan: 400, feebas: 100, pidgey: 12, weedle: 12, caterpie: 12, wurmple: 12,
  rattata: 25, rattata_alolan: 25, eevee: 25, sunkern: 50, rhydon: 100, machoke: 100, haunter: 100, dragonair: 100, metang: 100,
  pupitar: 100, shelgon: 100, larvitar: 25, bagon: 25, beldum: 25, dratini: 25, gastly: 25, gible: 25, gabite: 100, riolu: 50,
  swinub: 25, piloswine: 100, rhyhorn: 25, munchlax: 50, chansey: 50, tinkatink: 25, tinkatuff: 100, rookidee: 25, corvisquire: 100,
  mankey: 50, primeape: 100, fletchling: 25, fletchinder: 100, fuecoco: 25, crocalor: 100, mareep: 25, flaaffy: 100, fidough: 50,
  drilbur: 50, cubone: 50, wooper: 50, wooper_paldean: 50, dewpider: 50, spearow: 50, slakoth: 25, vigoroth: 100, frillish: 50,
  piplup: 25, prinplup: 100, totodile: 25, croconaw: 100, sobble: 25, drizzile: 100, charmander: 25, charmeleon: 100, mudkip: 25,
  marshtomp: 100, machop: 25, timburr: 50, gurdurr: 200, teddiursa: 50, ursaring: 100, roggenrola: 50, boldore: 200, litwick: 25, lampent: 100,
  nickit: 50, flabebe: 25, floette: 100, tympole: 25, palpitoad: 100, scorbunny: 25, raboot: 100, grookey: 25, thwackey: 100, vulpix: 50,
  vulpix_alolan: 50, ralts: 25, kirlia: 100, electabuzz: 100, magmar: 100, sneasel: 100, duskull: 25, dusclops: 100, larvesta: 400,
};
function evolveCandy(index, fromId, toId) {
  const from = baseSpeciesId(index, fromId);
  if (EVOLVE_CANDY_OVERRIDES[from] !== undefined) return EVOLVE_CANDY_OVERRIDES[from];
  const p = index.byId.get(from);
  const isFirst = !p?.family?.parent;
  const hasGrandchild = (p?.family?.evolutions ?? []).some((e) => (index.byId.get(e)?.family?.evolutions ?? []).length);
  return isFirst ? (hasGrandchild ? 25 : 50) : 100;
}

/** Path of evolution steps from one id to a descendant: [[from, to], ...]. */
function evolutionPath(index, fromId, toId) {
  const queue = [[fromId, []]];
  const seen = new Set([fromId]);
  while (queue.length) {
    const [id, path] = queue.shift();
    if (id === toId) return path;
    for (const next of [...(index.byId.get(id)?.family?.evolutions ?? []), ...(FORM_CHANGES[id] ?? [])]) {
      if (!seen.has(next)) { seen.add(next); queue.push([next, [...path, [id, next]]]); }
    }
  }
  return null;
}

function moveFlags(movesText) {
  const t = movesText || '';
  return {
    elite: (t.match(/\(Elite[^)]*\)/gi) || []).length,
    cd: /\((CD|Community Day)[^)]*\)/i.test(t),
    legacy: /\(legacy[^)]*\)/i.test(t),
    plusMove: /\s\+\s/.test(t), // "Move A + Move B" means a second charged move; "Future Sight+" does not
  };
}

/**
 * Analyse a box. Returns { pokemon: [...per-Pokémon analyses], builds, gaps, hygiene }.
 * ctx = { gm, tiers, rankings }
 */
function analyseBox(box, ctx) {
  const { gm, tiers, rankings } = ctx;
  const pokemon = [];
  const ownedBase = new Set();       // base species ids present in the box (any variant)
  const ownedIds = new Set();

  for (const p of box) {
    const r = resolveSpecies(gm, p.name, { form: p.form, shadow: p.shadow });
    if (!r) { pokemon.push({ p, unresolved: true }); continue; }
    ownedIds.add(r.speciesId); ownedBase.add(baseSpeciesId(gm, r.speciesId));
    const reach = [r.speciesId, ...evolutionsOf(gm, r.speciesId), ...formChangesOf(gm, r.speciesId)];
    const targets = new Set(reach);
    if (!p.shadow) for (const id of reach) for (const m of megaIdsOf(gm, id)) targets.add(m);

    const hits = [];
    for (const id of targets) {
      for (const e of tiers.bySpecies.get(id) || []) {
        // A Gigantamax entry is only ever satisfied by a Gigantamax catch, which an export cannot show: never credit it to a box Pokémon.
        if (e.area === 'max' && /gigantamax|g-max/i.test(e.name)) continue;
        // Mega targets are the same Pokémon plus Mega Energy: credit them to the base target.
        const targetId = /_(mega(_[xy])?|primal)$/.test(id) ? baseSpeciesId(gm, id) : id;
        hits.push({ kind: 'tier', area: e.area, section: e.section, tier: e.tier, name: e.name, targetId, viaMega: targetId !== id ? id : null, needsDynamax: e.area === 'max', moves: e.moves, obtain: e.obtain, notes: e.notes });
      }
      for (const [league, map] of Object.entries(rankings.byLeague)) {
        const row = map.get(id);
        if (row && row.score >= PVP_SCORE[league]) {
          const already = hits.some((h) => h.kind === 'tier' && h.area === league && h.targetId === id);
          if (!already) hits.push({ kind: 'rank', area: league, section: null, tier: row.score >= 92 ? 'S' : row.score >= 90 ? 'A' : 'B', name: gm.byId.get(id).speciesName, targetId: id, moves: row.moveset.join(' / '), rank: row.rank, score: row.score });
        }
      }
    }
    pokemon.push({ p, resolved: r, hits });
  }

  // Builds: one per (Pokémon, targetId), aggregating the areas it serves.
  const builds = [];
  for (const entry of pokemon) {
    if (entry.unresolved) continue;
    const { p, resolved: r, hits } = entry;
    const byTarget = new Map();
    for (const h of hits) { if (!byTarget.has(h.targetId)) byTarget.set(h.targetId, []); byTarget.get(h.targetId).push(h); }
    for (const [targetId, ths] of byTarget) {
      // Value: raids count each attacking type covered (up to three); other areas count once at their best tier.
      // PvP areas are scaled by this exact Pokémon's rank in that league from the export (squared: a mid-rank spread is worth little).
      const areas = new Map();
      const raidTypes = new Map();
      for (const h of ths) {
        const w = TIER_W[h.tier];
        if (h.area === 'raids' && h.section && h.section !== 'S tier — build first' && !/tier/i.test(h.section)) { if (!raidTypes.has(h.section) || raidTypes.get(h.section) < w) raidTypes.set(h.section, w); }
        if (!areas.has(h.area) || areas.get(h.area) < w) areas.set(h.area, w);
      }
      const leagueQ = (a) => {
        const league = a === 'gl' ? 'great' : a === 'ul' ? 'ultra' : 'master';
        const c = p.pvp?.[league];
        const same = c && resolveSpecies(gm, c.name, { form: c.form })?.speciesId === baseSpeciesId(gm, targetId);
        return same && c.rankPct != null ? 0.15 + 0.85 * (c.rankPct / 100) ** 2 : 0.6;
      };
      let value = 0;
      for (const [area, w] of areas) {
        if (area === 'raids') value += [...raidTypes.values()].sort((x, y) => y - x).slice(0, 3).reduce((s, x) => s + x, 0) || w;
        else if (['gl', 'ul', 'ml'].includes(area)) value += w * AREA_W[area] * leagueQ(area);
        else value += w * AREA_W[area];
      }
      const bestTier = ths.reduce((t, h) => (TIER_W[h.tier] > TIER_W[t] ? h.tier : t), 'B');
      const isMega = false;
      const viaMega = ths.some((h) => h.viaMega);
      const needsDynamax = ths.some((h) => h.needsDynamax);
      const stepTarget = targetId;
      const path = evolutionPath(gm, r.speciesId, stepTarget) ?? [];
      const evoCandy = path.reduce((s, [from, to]) => s + (FORM_CHANGES[from]?.includes(to) ? 0 : evolveCandy(gm, from, to)), 0);
      const formChange = path.some(([from, to]) => FORM_CHANGES[from]?.includes(to));
      // Costing: the most demanding area decides the target level; PvP uses the export's own figures when they match the target.
      const flags = { shadow: p.shadow, purified: p.purified, lucky: p.lucky };
      const level = p.level ?? 20;
      const pvpAreas = [...areas.keys()].filter((a) => ['gl', 'ul', 'ml'].includes(a));
      const otherAreas = [...areas.keys()].filter((a) => !pvpAreas.includes(a));
      // The export knows this exact Pokémon's cost to its best level in each league; take the league where it ranks best.
      let pvpCost = null;
      for (const a of pvpAreas) {
        const league = a === 'gl' ? 'great' : a === 'ul' ? 'ultra' : 'master';
        const c = p.pvp?.[league];
        if (c && c.dust !== null && resolveSpecies(gm, c.name, { form: c.form })?.speciesId === baseSpeciesId(gm, targetId)) {
          if (!pvpCost || (c.rankPct ?? 0) > (pvpCost.rankPct ?? 0)) pvpCost = { league: a, dust: c.dust, candy: c.candy, rankPct: c.rankPct, rank: c.rank };
        }
      }
      let targetLevel = otherAreas.length ? Math.max(...otherAreas.map((a) => TARGET_LEVEL[a])) : Math.max(...pvpAreas.map((a) => TARGET_LEVEL[a]));
      let cost = powerUpCost(level, Math.max(level, targetLevel), flags);
      if (pvpCost && !otherAreas.length) { cost = { dust: pvpCost.dust, candy: pvpCost.candy, xl: 0, steps: 0 }; targetLevel = null; }
      const mf = moveFlags(ths.map((h) => h.moves).join(' '));
      const secondMove = mf.plusMove ? secondMoveCost(gm.byId.get(stepTarget)?.thirdMoveCost ?? 50000, flags) : { dust: 0, candy: 0 };
      const totalDust = cost.dust + secondMove.dust;
      const totalCandy = (pvpCost && !otherAreas.length ? cost.candy : cost.candy + evoCandy) + secondMove.candy;
      const effort = totalDust / 100000 + totalCandy / 100 + cost.xl / 148 + mf.elite * 1.5 + (formChange ? 1.5 : 0) + (viaMega ? 0.3 : 0);
      // IV quality: PvP uses the export's rank % (squared, so a mid-rank spread is worth little); everything else uses IV average, mildly.
      const ivQ = (p.ivPercent ? 0.8 + 0.2 * (p.ivPercent / 100) : 0.9) * (evoCandy === 0 && !formChange ? 1.3 : 1); // already the final form: phase 1 material
      builds.push({
        pokemon: p, speciesId: r.speciesId, targetId, targetName: gm.byId.get(targetId)?.speciesName ?? targetId,
        areas: [...areas.keys()], bestTier, value: Math.round(value * 100) / 100, hits: ths, path, evoCandy, formChange, viaMega, needsDynamax,
        level, targetLevel, cost: { ...cost, dust: totalDust, candy: totalCandy, secondMove }, pvpCost, moveFlags: mf,
        effort: Math.round(effort * 100) / 100, score: Math.round((value ** 1.5 * ivQ) / Math.max(0.3, effort) ** 0.6 * 100) / 100,
      });
    }
  }
  builds.sort((a, b) => b.score - a.score);
  // One row per (species, target): the best copy carries the build, the rest are spares.
  const seenBuild = new Map();
  for (const b of builds) {
    const key = `${b.speciesId}|${b.targetId}`;
    if (seenBuild.has(key)) { seenBuild.get(key).spares.push(b.pokemon); b.duplicate = true; } else { b.spares = []; seenBuild.set(key, b); }
  }
  const primaryBuilds = builds.filter((b) => !b.duplicate);

  // Gaps: S and A tier species with nothing in the box that can become them.
  const gaps = [];
  const seenGap = new Set();
  for (const e of tiers.entries) {
    if (!/^[SA]$/.test(e.tier)) continue;
    const base = baseSpeciesId(gm, e.speciesId);
    const reachable = [...ownedIds].some((id) => {
      const reach = [id, ...evolutionsOf(gm, id), ...formChangesOf(gm, id)];
      if (reach.includes(e.speciesId)) return true;
      return !id.endsWith('_shadow') && reach.some((r) => megaIdsOf(gm, r).includes(e.speciesId));
    });
    if (reachable) continue;
    const key = `${e.area}|${e.speciesId}`;
    if (seenGap.has(key)) continue; seenGap.add(key);
    gaps.push({ area: e.area, section: e.section, tier: e.tier, name: e.name, speciesId: e.speciesId, obtain: e.obtain, haveBase: ownedBase.has(base) });
  }
  gaps.sort((a, b) => TIER_W[b.tier] - TIER_W[a.tier] || a.area.localeCompare(b.area));

  // Hygiene: duplicates by resolved species; keep the best IV (and anything with a tier-S hit), transfer the rest.
  const groups = new Map();
  for (const e of pokemon) { if (e.unresolved) continue; const k = e.resolved.speciesId; if (!groups.has(k)) groups.set(k, []); groups.get(k).push(e); }
  const hygiene = [];
  for (const [id, es] of groups) {
    if (es.length < 2) continue;
    const sorted = [...es].sort((a, b) => (b.p.ivPercent ?? 0) - (a.p.ivPercent ?? 0) || b.p.cp - a.p.cp);
    const legendary = (gm.byId.get(id)?.tags ?? []).some((t) => ['legendary', 'mythical', 'ultrabeast'].includes(t));
    const keepCount = legendary ? Math.min(2, es.length) : 1;
    hygiene.push({ speciesId: id, name: gm.byId.get(id).speciesName, count: es.length, keep: sorted.slice(0, keepCount).map((e) => e.p), transfer: sorted.slice(keepCount).map((e) => e.p) });
  }
  hygiene.sort((a, b) => b.transfer.length - a.transfer.length);

  return { pokemon, builds: primaryBuilds, allBuilds: builds, gaps, hygiene };
}
return { AREA_LABEL, analyseBox };
});
__def("src/csv.js", function () {
// Minimal RFC 4180 CSV parser (quotes, escaped quotes, CRLF). Returns array of objects keyed by header.
function parseCsv(text) {
  const rows = [];
  let row = [], field = '', inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; } else inQuotes = false;
      } else field += c;
    } else if (c === '"') inQuotes = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n' || c === '\r') {
      if (c === '\r' && text[i + 1] === '\n') i++;
      row.push(field); field = '';
      if (row.length > 1 || row[0] !== '') rows.push(row);
      row = [];
    } else field += c;
  }
  if (field !== '' || row.length) { row.push(field); rows.push(row); }
  if (!rows.length) return [];
  const header = rows[0].map((h) => h.replace(/^﻿/, '').trim());
  return rows.slice(1).map((r) => Object.fromEntries(header.map((h, i) => [h, r[i] ?? ''])));
}
return { parseCsv };
});
__def("src/import/pokegenie.js", function () {
const { parseCsv } = __use("src/csv.js");
const num = (v) => (v === '' || v === undefined ? null : Number(v));
const pct = (v) => (v === '' || v === undefined ? null : Number(String(v).replace('%', '')));

/**
 * Parse a Poke Genie storage export into normalised records.
 * Shadow/Purified column: 0 = neither, 1 = shadow, 2 = purified.
 */
function importPokeGenie(csvText) {
  return parseCsv(csvText).map((r) => {
    const sp = Number(r['Shadow/Purified'] || 0);
    const ivs = { atk: num(r['Atk IV']), def: num(r['Def IV']), hp: num(r['Sta IV']) };
    const ivsKnown = ivs.atk !== null && ivs.def !== null && ivs.hp !== null;
    return {
      source: 'pokegenie',
      index: num(r.Index),
      name: r.Name.trim(),
      form: (r.Form || '').trim(),          // as Poke Genie writes it: '', 'Normal', 'Galar', 'Mega Y', 'Hero', '10%' ...
      gender: r.Gender || '',
      cp: num(r.CP),
      hp: num(r.HP),
      ivs: ivsKnown ? ivs : null,
      ivPercent: num(r['IV Avg']),
      levelMin: num(r['Level Min']),
      levelMax: num(r['Level Max']),
      level: num(r['Level Min']),          // Poke Genie's best estimate; equals levelMax when IVs are exact
      moves: [r['Quick Move'], r['Charge Move'], r['Charge Move 2']].map((m) => (m || '').trim()).filter(Boolean),
      shadow: sp === 1,
      purified: sp === 2,
      lucky: r.Lucky === '1',
      favorite: r.Favorite === '1',
      dust: num(r.Dust),                    // power-up dust at current level, as shown in game
      scanDate: r['Scan Date'] || '',
      pvp: {
        great: { rankPct: pct(r['Rank % (G)']), rank: num(r['Rank # (G)']), name: r['Name (G)'], form: r['Form (G)'], dust: num(r['Dust Cost (G)']), candy: num(r['Candy Cost (G)']) },
        ultra: { rankPct: pct(r['Rank % (U)']), rank: num(r['Rank # (U)']), name: r['Name (U)'], form: r['Form (U)'], dust: num(r['Dust Cost (U)']), candy: num(r['Candy Cost (U)']) },
        master: { rankPct: pct(r['Rank % (L)']), rank: num(r['Rank # (L)']), name: r['Name (L)'], form: r['Form (L)'], dust: num(r['Dust Cost (L)']), candy: num(r['Candy Cost (L)']) },
      },
      markedForPvp: (r['Marked for PvP use'] || '').trim() !== '',
    };
  });
}
return { importPokeGenie };
});
// The entry of the app-core bundle, appended by build-js-bundle.mjs inside the bundle's scope (so it can
// reach the module registry). It defines the one global, PogoCore. Raw module functions are exposed as
// they are; the *JSON functions are what the app calls: JSON text in and out (no bridged objects), with
// the indexed game master, tiers and rankings kept in the context after load().
// JSON.stringify drops undefined; the replacer turns the Maps and Sets the advisor uses into plain data.
const P = __use('src/extract/pipeline.js'), B = __use('src/extract/batch.js'), G = __use('src/gamemaster.js'), D = __use('src/data.js'),
  A = __use('src/advise.js'), I = __use('src/import/pokegenie.js');
let ctx = null;
const need = () => { if (!ctx) throw new Error('PogoCore.load(gamemaster, tiers, rankings) has not been called'); return ctx; };
const replacer = (k, v) => (v instanceof Map ? Object.fromEntries(v) : v instanceof Set ? [...v] : v);
const out = (v) => JSON.stringify(v, replacer);
global.PogoCore = {
  // raw module functions (objects in, objects out)
  indexGamemaster: G.indexGamemaster, indexTiers: D.indexTiers, indexRankings: D.indexRankings,
  finish: P.finish, cpOptions: P.cpOptions, toPokeGenieCsv: P.toPokeGenieCsv, POKEGENIE_COLUMNS: P.POKEGENIE_COLUMNS,
  mergeClips: B.mergeClips, importPokeGenie: I.importPokeGenie, analyseBox: A.analyseBox, AREA_LABEL: A.AREA_LABEL,
  // JSON-text layer
  load(gmText, tiersText, rankingsText) {
    ctx = { gm: G.indexGamemaster(JSON.parse(gmText)), tiers: D.indexTiers(JSON.parse(tiersText)), rankings: D.indexRankings(JSON.parse(rankingsText)) };
    return true;
  },
  finishJSON(readingsText) { return out(P.finish(JSON.parse(readingsText), need().gm)); },
  // scanDateMs: epoch milliseconds, shown in the device's local time (like new Date() in the CLI)
  csvJSON(rowsText, scanDateMs) { return P.toPokeGenieCsv(JSON.parse(rowsText), { scanDate: scanDateMs == null ? new Date() : new Date(scanDateMs) }); },
  mergeClipsJSON(clipsText, optionsText) { return out(B.mergeClips(JSON.parse(clipsText), optionsText ? JSON.parse(optionsText) : undefined)); },
  importPokeGenieJSON(csvText) { return out(I.importPokeGenie(csvText)); },
  adviseJSON(boxText) { const r = A.analyseBox(JSON.parse(boxText), need()); return out({ builds: r.builds, gaps: r.gaps, hygiene: r.hygiene, pokemon: r.pokemon, areaLabel: A.AREA_LABEL }); },
};
})(typeof globalThis !== "undefined" ? globalThis : this);
